### ISSUE TITLE
Docker 在 Mac 下的 2375 端口问题

### ISSUE THREAD

**Issue by penglongli** [penglongli/blog#68]

**Comment by yingzhuo** [comment]
问题解决了， 用`docker-compose`相对来说方便一点。

`docker-compose.yml`内容如下:

```yml
version: "3.5"

services:
  redis:
    image: "alpine/socat"
    container_name: socat
    restart: "always"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "2375:2375"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

networks:
  default:
    external:
      name: my_network
```
